name: Publish
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: 0.2.0+1.21.1
  VERSION_TYPE: beta

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' # @AnthonyWC on GH, https://github.com/orgs/community/discussions/26724#discussioncomment-3253096
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Datagen
        run: ./gradlew runDatagen

      - name: Upload Generated Data
        uses: actions/upload-artifact@v4
        with:
          name: GeneratedData
          path: src/main/generated/
          overwrite: true

      - name: Build
        run: ./gradlew build

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: JARs
          path: build/libs/*

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: |
            build/libs/!(*-@(dev|sources|javadoc|all)).jar 
            build/libs/*-@(dev|sources|javadoc).jar

          version-type: ${{ env.VERSION_TYPE }}

          modrinth-id: DZJzhD8k
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: "v${{ env.VERSION }}"
          github-token: ${{ secrets.GH_TOKEN }}

          changelog-file: CHANGELOG.md

          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"